name = "tauri-update-server"
workers_dev = true
compatibility_date = "2022-03-26"
main = "src/index.ts"

[vars]
GITHUB_ACCOUNT = 'Dreaming-Codes'
GITHUB_REPO = 'discord-source'

[build]
command = "npm install && npm run build"
